EmotionActionTypes = ->

  this.FETCH_DATA = 'EMOTION_FETCH_DATA'
  this.TAGS_INIT = 'EMOTION_TAGS_INIT'
  this.SET_FILTER = 'EMOTION_SET_FILTER'
  this.SET_TARGET = 'EMOTION_SET_TARGET'
  this.SET_COMMAND = 'EMOTION_SET_COMMAND'

  this.FETCH_DATA_DONE = 'EMOTION_FETCH_DATA_DONE'
  this.GET_FILTER_RESULT = 'EMOTION_GET_FILTER_RESULT'
  this.SET_TARGET_DONE = 'EMOTION_SET_TARGET_DONE'
  this.SET_COMMAND_DONE = 'EMOTION_SET_COMMAND_DONE'

  return